<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9sVf5mO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9sVf5mO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9sVf5mO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9sVf5mO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9sVf5mO\App_KernelDevDebugContainer([
    'container.build_hash' => '9sVf5mO',
    'container.build_id' => '7ef42fab',
    'container.build_time' => 1595093762,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9sVf5mO');
